---
abstract: 'Perl interface to FilmAffinity'
author:
  - 'William Belle <william.belle@gmail.com>'
build_requires:
  File::Find::Rule: '0.33'
  Test::JSON: '0.11'
  Test::LongString: '0.15'
  Test::MockObject: '1.2'
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FilmAffinity-UserRating
provides:
  FilmAffinity::Movie:
    file: lib/FilmAffinity/Movie.pm
    version: '0.06'
  FilmAffinity::UserRating:
    file: lib/FilmAffinity/UserRating.pm
    version: '0.06'
  FilmAffinity::Utils:
    file: lib/FilmAffinity/Utils.pm
    version: '0.06'
requires:
  Encode: '2.57'
  HTML::TreeBuilder: '5.03'
  HTML::TreeBuilder::XPath: '0.14'
  IO::All: '0.59'
  JSON: '2.9'
  LWP::RobotUA: '6.03'
  List::Compare: '0.38'
  Moose: '2.12'
  MooseX::Privacy: '0.05'
  Text::Trim: '1.02'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
